root_dir = '$DOTFILES'

[targets_dirs]
'~' = ['misc/home', 'zsh', 'git', 'python']
'~/Library/Application Support/Code/User' = ['vscode']
'~/Library/Application Support/Anki2/addons21/field_matcher' = [
    '~/garage/Dev/Projects/Python/anki-field-matcher/field_matcher',
]
