add_newline = false

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[line_break]
disabled = true

[directory]
truncation_length = 5

[git_branch]
# Remove 'on'
format = '[$symbol$branch(:$remote_branch)]($style) '

[cmd_duration]
# Remove 'took'
format = '[$duration]($style) '
# Grey
style = 'fg:246'

[python]
# Remove 'via'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# Remove 'v'
version_format = '${raw}'

[package]
# Remove 'is'
format = '[$symbol$version]($style) '
# Remove 'v'
version_format = '${raw}'

[docker_context]
# Remove 'via' and $context. Default format: 'via [$symbol$context]($style) '
format = '[$symbol]($style)'

[kubernetes]
format = '[$symbol]($style) '
style = 'blue'
disabled = false
contexts = [
    { context_pattern = 'digital_ocean', symbol = '🌊' },
    { context_pattern = 'azure', symbol = '🌤 ' },
    { context_pattern = '.*', symbol = '☸' },
]
